name: Content
on:
  push:
    branches:
      - main
    paths:
      - 'content/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Site build
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository: erofteev-dev/platform
          event-type: content_update
